FEATURE: Add optimized picture (see #383 from Porphyry)
Hypertopic/Steatite pull request #13
Opened 2021-06-17 12:45 UTC by Antoine-Guyot

@benel @albertelombo 

Adding an optimized version of the picture in order to improve the loading time in response to the 383 ticket from Porphyry.

The modifications could not be tested.

2021-06-18 09:05 UTC, benel commented
@Antoine-Guyot @albertelombo 

J'ai corrigé le script de construction de l'image docker.

Vous pouvez donc (à condition de récupérer mon dernier commit), tester votre code en construisant l'image à partir de votre dossier de travail puis en la lançant : 
```shell
docker build -t steatite:dev .
docker run -p 8000:80 -d steatite:dev  
```

2021-06-18 10:47 UTC, Antoine-Guyot commented
@benel @albertelombo 

J'ai pu lancer Steatite, cependant l'image optimisée ne semble pas fonctionner. J'obtiens l'erreur suivante :
```
Cannot execute the following command:

anytopnm ../data/c4ced98095164137e2df8ab7aa6e9e3740b12a96| pnmtojpeg >../optimized/c4ced98095164137e2df8ab7aa6e9e3740b12a96....
```

Mon problème est que je n'ai pas l'impression que mes modifications soient prises en compte en temps réelle et je ne sais pas comment appliquer mes changements sur mon localhost.

2021-06-18 11:15 UTC, benel commented
> Mon problème est que je n'ai pas l'impression que mes modifications soient prises en compte en temps réelle et je ne sais pas comment appliquer mes changements sur mon localhost.

Je vous confirme que ce n'est pas en temps réel : il faut construire votre image puis la lancer. Donc ce que vous testez (sur le port localhost:8000) c'est le code que vous aviez au moment où vous avez construit l'image.

2021-06-18 11:21 UTC, benel commented
```
Cannot execute the following command:
anytopnm ../data/c4ced98095164137e2df8ab7aa6e9e3740b12a96| pnmtojpeg >../optimized/c4ced98095164137e2df8ab7aa6e9e3740b12a96....
```

Et pour information, c'est précisément l'erreur que vous auriez si vous n'aviez pas intégré mon commit... Êtes-vous certain d'avoir `libtiff5` dans votre `Dockerfile` ?

2021-06-18 11:31 UTC, benel commented
> c4ced98095164137e2df8ab7aa6e9e3740b12a96

Vous avez déposé l'image par l'interface Web ?

2021-06-18 11:45 UTC, benel commented
Et vérifiez d'abord que l'interface fonctionne parfaitement (upload, vignettes...) avant de tester ce qui est spécifique à votre contribution (corpus, item, optimized).

2021-06-18 12:11 UTC, Antoine-Guyot commented
J'ai bien récupéré votre commit et `libtiff5 `apparaît bien dans `Dockerfile`.
L'interface semble fonctionner correctement, elle s'affiche bien et j'ai pu utiliser l'upload pour déposer mon image.

2021-06-18 12:15 UTC, benel commented
> j'ai pu utiliser l'upload pour déposer mon image.

Après l'upload, vous voyez sa vignette ?

2021-06-18 12:19 UTC, benel commented
Une fois que vous avez ouvert l'image à partir de l'interface, remplacez `picture` par `item/MISC`. Vous allez voir si vous voyez vos modifications.

2021-06-18 12:20 UTC, Antoine-Guyot commented
Oui, j'ai bien la vignette. Quand je clique dessus je suis dirigé vers `http://localhost:8000/picture/c4ced98095164137e2df8ab7aa6e9e3740b12a96` et si je change `picture` en `optimized` j'obtiens l'erreur. Si je met `thumbnail` tout va bien.

2021-06-18 12:27 UTC, benel commented
> si je change picture en optimized j'obtiens l'erreur. Si je met thumbnail tout va bien.

Si je demandais `item/MISC` (et non `optimized`  puisque vous m'aviez déjà dit que ça ne marchait pas) c'est parce que l'intégration est plus simple : on verra tout de suite s'il y a vos modifications ou pas.

2021-06-18 12:38 UTC, Antoine-Guyot commented
Excusez-moi, je n'avais pas vu ce commentaire. J'obtiens ceci :
```
{"rows":[
  {"key":["MISC", "c4ced98095164137e2df8ab7aa6e9e3740b12a96"], "value":{"name":"test2.jfif"}},
  {"key":["MISC", "c4ced98095164137e2df8ab7aa6e9e3740b12a96"], "value":{"original":"https://localhost:8000/picture/c4ced98095164137e2df8ab7aa6e9e3740b12a96"}},
  {"key":["MISC", "c4ced98095164137e2df8ab7aa6e9e3740b12a96"], "value":{"resource":"https://localhost:8000/optimized/c4ced98095164137e2df8ab7aa6e9e3740b12a96"}},
  {"key":["MISC", "c4ced98095164137e2df8ab7aa6e9e3740b12a96"], "value":{"thumbnail":"https://localhost:8000/thumbnail/c4ced98095164137e2df8ab7aa6e9e3740b12a96"}}
,
    {"key":["MISC", "c4ced98095164137e2df8ab7aa6e9e3740b12a96"], "value":{"created":"2019-02-24"}}
  ,
    {"key":["MISC", "c4ced98095164137e2df8ab7aa6e9e3740b12a96"], "value":{"spatial":"48 deg 18' 26.88\" N, 4 deg 19' 18.32\" E"}}
]}
```
La ligne avec optimized apparaît bien

2021-06-18 12:47 UTC, benel commented
> La ligne avec optimized apparaît bien

Oui. Vos modifications sont donc bien prises en compte.

Pour déboguer, je vous invite à lancer dans la console de votre conteneur la commande donnée par le message d'erreur. Vous verrez ainsi précisément ce que vous dit le système.

Si vous utilisez DockerDesktop, c'est la petite icône `>_` (CLI) qui vous permet d'ouvrir la console d'un conteneur.

2021-06-18 12:54 UTC, Antoine-Guyot commented
J'obtiens l'erreur suivante :
```
cannot create ../optimized/c4ced98095164137e2df8ab7aa6e9e3740b12a96....: Directory nonexistent
/usr/bin/anytopnm: '../data/c4ced98095164137e2df8ab7aa6e9e3740b12a96' does not exist or is not a file
```
On dirait qu'il y a une erreur à la création et à la récupération de l'image

2021-06-18 13:10 UTC, benel commented
> cannot create ../optimized/c4ced98095164137e2df8ab7aa6e9e3740b12a96....: Directory nonexistent

Il faut que vous créiez votre dossier dans le `Dockerfile` : https://github.com/Hypertopic/Steatite/blob/master/Dockerfile#L12

2021-06-18 13:24 UTC, Antoine-Guyot commented
J'ai modifié Dockerfile et tout fonctionne parfaitement, mon image de 2,46 Mo est passée à 1,27 Mo. J'ai donc commit ce changement. Merci pour votre aide.

2021-06-21 15:05 UTC, benel requested changes
Merci @Antoine-Guyot pour cette fonctionnalité importante.

Comme indiqué dans les commentaires ligne à ligne du Dockerfile, il y a de petites erreurs de compréhension des commandes Unix qui font que ça pourrait être plus élégant en fusionnant les commandes de même type...

Par ailleurs, pour l'historique Git, merci d'avance : 
- de condenser cette contribution sous forme d'un un seul _commit_ avec un titre du genre `FEATURE: Get the main resource as an optimized picture.` ;
- d'indiquer à la troisième ligne du message de commit le co-auteur, s'il y en a un, avec la syntaxe `Co-Authored-By: Prenom Nom <e-mail@acme.com>` ;
- de faire effectivement une référence au ticket de Porphyry, par exemple à la cinquième ligne du commit, avec une phrase du type `For more details, see Hypertopic/Porphyry#383.` (cela créera un lien birectionnel entre le commit et le ticket).

2021-06-22 09:26 UTC, benel requested changes
Merci @Antoine-Guyot pour ces modifications.

Un micro-détail : en changeant les indentations dans `src/view/item.json` , vous rendez la consultation du "diff" plus difficile. On voit moins le fait que l'URI de `resource` est passé dans `original` et que c'est une nouvelle URI en `optimized` qui devient celle de `resource`.
C'est pour cette raison qu'en général on déconseille de faire dans les mêmes commits de vraies contributions et des changements de style.

Pensez bien à tout regrouper dans **un seul commit** (avec le dernier descriptif, il était très bien). Vous voyez comment faire ?

2021-06-22 09:38 UTC, Antoine-Guyot commented
@benel

J'ai essayé de squash les commits en faisant un rebase mais je ne crois pas que cela ai fonctionné. Et @albertelombo n'apparait pas comme auteur alors que j'ai ajouté `Co-Authored-By`. Du coup je ne vois pas comment faire pour tout regrouper.

Je ne me souviens pas avoir changé les indentations de `src/view/item.json`, je ne sais pas comment corriger ça.

2021-06-22 09:53 UTC, benel commented
> Et @albertelombo n'apparait pas comme auteur alors que j'ai ajouté Co-Authored-By. 

C'est effectivement bizarre. La syntaxe semble pourtant correcte...

> J'ai essayé de squash les commits en faisant un rebase mais je ne crois pas que cela ai fonctionné. 

Peut-être que lors du push vous avez oublié le paramètre `--force` (en effet vous réécrivez l'historique, il faut donc rassurer l'entrepôt sur le fait que vous savez ce que vous faites).

2021-06-22 10:02 UTC, benel commented
> Je ne me souviens pas avoir changé les indentations de src/view/item.json, je ne sais pas comment corriger ça.

Il y avait une indentation de 4 espaces (et non de 2). Après les avoir réintroduits, on ne devrait plus voir que 2 lignes modifiées dans le `diff` de `src/view/item.json` (par exemple dans l'onglet "files changed" de cette _pull request_).

2021-06-22 10:26 UTC, Antoine-Guyot commented
@benel 

Il ne reste maintenant qu'un seul commit, c'était bien le paramètre `--force` que j'avais oublié. J'ai également rectifié mon erreur d'indentation.
Par contre le co-auteur n'apparait toujours pas.

2021-06-22 13:11 UTC, benel commented
Intégré en tant que e67ae3fdc8b7acd27cc2b04941c392ddd7e7fbb0.
Bravo à @Antoine-Guyot et @albertelombo 🎉

2021-06-22 13:11 UTC, closed without merging